---
title: "p8105_hw06_hc3448"
author: "HsiYu Chen"
date: "2024-11-28"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
#library(p8105.datasets)
library(modelr)
#library(readr)
#library(GGally)

set.seed(1)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Problem 1

```{r message=FALSE}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```


```{r}
bootstrap_df = 
  weather_df |> 
  modelr::bootstrap(5000) |> 
  mutate(
    models = map(strap, \(df) lm(tmax ~ tmin, data = df)),
    glance_result = map(models, broom::glance),
    tidy_result = map(models, broom::tidy)
  ) |> 
  unnest(tidy_result) |>
  select(term, estimate, glance_result) |>
  pivot_wider(
    names_from = term,
    values_from = estimate
  ) |>
  mutate(log_beta = log(`(Intercept)`*tmin)) |>
  unnest(glance_result) |>
  select(log_beta, adj.r.squared)

bootstrap_df |> head(5) |> knitr::kable()
```

```{r}
ggplot(bootstrap_df, aes(x = adj.r.squared)) +
      geom_density()
```

```{r}
ggplot(bootstrap_df, aes(x = log_beta)) +
      geom_density()
```
## Problem 2

```{r}

```

